### ISSUE TITLE
Packages not installing on Ubuntu 18.04

### ISSUE THREAD

**Issue by mbound** [rickysarraf/apt-offline#157]
I am trying to install some packages across an offline Ubuntu server 18.04 LTS machine, but packages appear to not be installed.

the only error I keep getting even with `--verbose` mode is:
```
ERROR: Path for keyring is invalid: /etc/apt/trusted.gpg
```
However, in all cases packages are not upgraded or installed...
What's going on? Is something broken on Ubuntu 18.04?

Attaching log files and sig files.
[apt-offline.log](https://github.com/rickysarraf/apt-offline/files/7516334/apt-offline.log)
[apt-upgrade.log](https://github.com/rickysarraf/apt-offline/files/7516335/apt-upgrade.log)
[kernel-lowlatency-offline.log](https://github.com/rickysarraf/apt-offline/files/7516336/kernel-lowlatency-offline.log)
[utils1-offline.log](https://github.com/rickysarraf/apt-offline/files/7516337/utils1-offline.log)
.
[apt-offline.txt](https://github.com/rickysarraf/apt-offline/files/7516349/apt-offline.txt)
[kernel-lowlatency-offline.txt](https://github.com/rickysarraf/apt-offline/files/7516351/kernel-lowlatency-offline.txt)
[utils1-offline.txt](https://github.com/rickysarraf/apt-offline/files/7516352/utils1-offline.txt)
.

**Comment by rickysarraf** [comment]
I'm not sure what version of apt-offlien Ubuntu 18.04 ships. But, IIRC, this was fixed long ago in bd985441a147ac2bda073070796e2248481d08e8

**Comment by rickysarraf** [comment]
If it is possbile, can you try with the latest apt-offline from Debian Unstable ?
https://packages.debian.org/sid/apt-offline

**Comment by mbound** [comment]
@rickysarraf That's exactly the version I am using, 1.8.2-2
```
apt-offline_1.8.2-2_all.deb
```
I had the same problem with the one shipping with Ubuntu, which is 1.8.1, so I switched to 1.8.2-2.

**Comment by mbound** [comment]
According to someone, the keyring issue is not it?
https://askubuntu.com/questions/1201110/sudo-apt-offline-install-not-updating 

Also, one thing I noticed, when generating the sig file for `apt update` or `upgrade` with:
```
apt-offline --verbose set --update --upgrade apt-offline.sig
```
Some times some extra lines appear: 
```
26 standard security updates
```
that then prompt the get process to error out:
```
Downloading 26                                                             
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineLib.py", line 691, in run
    self.responseQueue.put( self.WorkerFunction( item, thread_name ) )
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 1271, in DataFetcher
    if DownloadPackages(url) is False and guiTerminateSignal is False:
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 1251, in DownloadPackages
    if FetcherInstance.download_from_web(url, pkgFile, Str_DownloadDir):
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 701, in download_from_web
    temp = urllib.request.urlopen(url)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 511, in open
    req = Request(fullurl, data)
  File "/usr/lib/python3.6/urllib/request.py", line 329, in __init__
    self.full_url = url
  File "/usr/lib/python3.6/urllib/request.py", line 355, in full_url
    self._parse()
  File "/usr/lib/python3.6/urllib/request.py", line 384, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '26'
```

**Comment by rickysarraf** [comment]
:-(

I need to seriously devote a weekend and do a new release.

This was reported earlier: https://github.com/rickysarraf/apt-offline/issues/147
And fixed in: https://github.com/rickysarraf/apt-offline/commit/50267a68844b70cff4c8d422df7d760a2595a65b

**Comment by mbound** [comment]
Yeah, but I guess these are 2 unrelated things, still not sure why packages are not installing.  The URIs are correct, because I did a manual parsing of the .sig file with:
```
cat utils1-offline.sig | cut -d\' -f 2 > utils1-offline-urls.txt
```
and then was able to wget the packages and install them all with `dpkg -i`

**Comment by rickysarraf** [comment]
Can you please share your full console output of all the commands being run ?

* `apt-offline set --verbose .......`
* `apt-offline get --verbose .......`
* `apt-offline install --verbose .......`

Thanks.

**Comment by gregvirgin** [comment]
I've been experiencing this for a while and working around it by explicitly listing the packages in my set command. Output has been like this before and after doing that. I think a lot of the comments above weren't the root cause but I'm not the expert. See attached files
[get.log](https://github.com/rickysarraf/apt-offline/files/7737212/get.log)
[install.log](https://github.com/rickysarraf/apt-offline/files/7737213/install.log)
[set.log](https://github.com/rickysarraf/apt-offline/files/7737214/set.log)
[apt-offline.sig.txt](https://github.com/rickysarraf/apt-offline/files/7737216/apt-offline.sig.txt)
.

**Comment by rickysarraf** [comment]
> I've been experiencing this for a while and working around it by explicitly listing the packages in my set command. Output has been like this before and after doing that. I think a lot of the comments above weren't the root cause but I'm not the expert. See attached files [get.log](https://github.com/rickysarraf/apt-offline/files/7737212/get.log) [install.log](https://github.com/rickysarraf/apt-offline/files/7737213/install.log) [set.log](https://github.com/rickysarraf/apt-offline/files/7737214/set.log) [apt-offline.sig.txt](https://github.com/rickysarraf/apt-offline/files/7737216/apt-offline.sig.txt) .

The sig file has below which should be fixed in `master`.

```
'http://us.archive.ubuntu.com/ubuntu/dists/focal-security/multiverse/cnf/Commands-all.xz' us.archive.ubuntu.com_ubuntu_dists_focal-security_multiverse_cnf_Commands-all 0 
10 standard security updates
'http://us.archive.ubuntu.com/ubuntu/pool/main/p/python3.8/libpython3.8_3.8.10-0ubuntu1~20.04.2_amd64.deb' libpython3.8_3.8.10-0ubuntu1~20.04.2_amd64.deb 1625088 MD5Sum:03df4f49c044ce0c0768af3ee5f51749
```


Below looks fine

```
[1;0m[1;36mVERBOSE: Item after split is: 'http://us.archive.ubuntu.com/ubuntu/dists/focal-security/multiverse/binary-all/Packages.xz' us.archive.ubuntu.com_ubuntu_dists_focal-security_multiverse_binary-all_Packages 0 

[1;0m[1;36mVERBOSE: Stripped item URL is: http://us.archive.ubuntu.com/ubuntu/dists/focal-security/multiverse/binary-all/Packages.xz
[1;0m[1;36mVERBOSE: Stripped item FILE is: us.archive.ubuntu.com_ubuntu_dists_focal-security_multiverse_binary-all_Packages
[1;0m[1;36mVERBOSE: Stripped item SIZE is: 0
[1;0m[1;36mVERBOSE: Stripped item CHECKSUM is: 
[1;0m[1;36mVERBOSE: Thread is Thread-1
[1;0mDownloading http://us.archive.ubuntu.com/ubuntu/dists/focal-security/multiverse/binary-all/Packages.xz                                                             
[1;36mVERBOSE: http://us.archive.ubuntu.com/ubuntu/dists/focal-security/multiverse/binary-all/Packages.xz - 404 - Not Found                                                             
[1;0m[1;36mVERBOSE: Will still try with other package uris
[1;0m[1;36mVERBOSE: http://us.archive.ubuntu.com/ubuntu/dists/focal-security/multiverse/binary-all/Packages.xz failed. Retry with the remaining possible formats
[1;0m
239 / 256 items: [##############################] 100.0% of 22 MiB
[1;36mVERBOSE: Retry download http://us.archive.ubuntu.com/ubuntu/dists/focal-security/multiverse/binary-all/Packages.bz2                                                             
[1;0m[1;36mVERBOSE: http://us.archive.ubuntu.com/ubuntu/dists/focal-security/multiverse/binary-all/Packages.bz2 - 404 - Not Found                                                             
[1;0m[1;36mVERBOSE: Will still try with other package uris
[1;0m[1;36mVERBOSE: Failed with URL http://us.archive.ubuntu.com/ubuntu/dists/focal-security/multiverse/binary-all/Packages.bz2                                                             
[1;0m
240 / 257 items: [##############################] 100.0% of 22 MiB
[1;36mVERBOSE: Retry download http://us.archive.ubuntu.com/ubuntu/dists/focal-security/multiverse/binary-all/Packages.gz                                                             
[1;0m[1;36mVERBOSE: http://us.archive.ubuntu.com/ubuntu/dists/focal-security/multiverse/binary-all/Packages.gz - 404 - Not Found                                                             
[1;0m[1;36mVERBOSE: Will still try with other package uris
[1;0m[1;36mVERBOSE: Failed with URL http://us.archive.ubuntu.com/ubuntu/dists/focal-security/multiverse/binary-all/Packages.gz                                                             
[1;0m
241 / 258 items: [##############################] 100.0% of 22 MiB
[1;36mVERBOSE: Retry download http://us.archive.ubuntu.com/ubuntu/dists/focal-security/multiverse/binary-all/Packages.lzma                                                             
[1;0m[1;36mVERBOSE: http://us.archive.ubuntu.com/ubuntu/dists/focal-security/multiverse/binary-all/Packages.lzma - 404 - Not Found                                                             
[1;0m[1;36mVERBOSE: Will still try with other package uris
[1;0m[1;36mVERBOSE: Failed with URL http://us.archive.ubuntu.com/ubuntu/dists/focal-security/multiverse/binary-all/Packages.lzma                                                             
[1;0m[1;36m[1;0m[1;36m[1;0m[1;36m[1;0m[1;36m[1;0m[1;36m[1;0m[1;36m[1;0m[1;36m[1;0m[1;32m[1;0m[1;36m[1;0m[1;36m[1;0m[1;36m[1;0m[1;36m[1;0m[1;36m[1;0m[1;36m[1;0m[1;36m[1;0m[1;36m[1;0m[1;36m[1;0m[1;36m[1;0m[1;36m[1;0m[1;36m[1;0m[1;36m[1;0m[1;36m[1;0m[1;36m[1;0m[1;36m[1;0m[1;36m[1;0m[1;36m[1;0m[1;36m[1;0m[1;36m[1;0m[1;36m[1;0m[1;36m[1;0m[1;31mERROR: Giving up on URL http://us.archive.ubuntu.com/ubuntu/dists/focal-security/multiverse/binary-all/Packages.lzma                                                             
[1;0m
242 / 259 items: [##############################] 100.0% of 22 MiB
[1;31m[1;0m[1;36mVERBOSE: Item before split is: 'http://us.archive.ubuntu.com/ubuntu/dists/focal-security/multiverse/i18n/Translation-en_US.xz' us.archive.ubuntu.com_ubuntu_dists_focal-security_multiverse_i18n_Translation-en%5fUS 0 

[1;0m[1;36mVERBOSE: Item after split is: 'http://us.archive.ubuntu.com/ubuntu/dists/focal-security/multiverse/i18n/Translation-en_US.xz' us.archive.ubuntu.com_ubuntu_dists_focal-security_multiverse_i18n_Translation-en%5fUS 0 
```
and in same log:

```
[1;0m[1;36m[1;0m[1;36m[1;0m[1;36m[1;0m[1;36m[1;0m[1;36m[1;0m[1;36m[1;0m[1;36m[1;0m[1;36m[1;0mException in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineLib.py", line 696, in run
    self.responseQueue.put( self.WorkerFunction( item, thread_name ) )
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 1335, in DataFetcher
    if DownloadPackages(PackageName, pkgFileWithType) is False and guiTerminateSignal is False:
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 1304, in DownloadPackages
    if FetcherInstance.download_from_web(PackageName, PackageFile, Str_DownloadDir):
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 709, in download_from_web
    temp = urllib.request.urlopen(url)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 509, in open
    req = Request(fullurl, data)
  File "/usr/lib/python3.8/urllib/request.py", line 328, in __init__
    self.full_url = url
  File "/usr/lib/python3.8/urllib/request.py", line 354, in full_url
    self._parse()
  File "/usr/lib/python3.8/urllib/request.py", line 383, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '10'
```
which is already fixed.


Below looks fine too.

```
[1;0m[1;36mVERBOSE: Synchronized file to /var/lib/apt/lists/us.archive.ubuntu.com_ubuntu_dists_focal-backports_main_binary-amd64_Packages
[1;0m[1;36mVERBOSE: /var/lib/apt/lists/us.archive.ubuntu.com_ubuntu_dists_focal-backports_main_binary-amd64_Packages file synced to APT.
[1;0m[1;32mus.archive.ubuntu.com_ubuntu_dists_focal-backports_main_binary-amd64_Packages.xz synced.
[1;0m[1;36mVERBOSE: Synchronized file to /var/lib/apt/lists/us.archive.ubuntu.com_ubuntu_dists_focal-backports_main_cnf_Commands-amd64
[1;0m[1;36mVERBOSE: /var/lib/apt/lists/us.archive.ubuntu.com_ubuntu_dists_focal-backports_main_cnf_Commands-amd64 file synced to APT.
[1;0m[1;32mus.archive.ubuntu.com_ubuntu_dists_focal-backports_main_cnf_Commands-amd64.xz synced.
[1;0m[1;36mVERBOSE: Synchronized file to /var/lib/apt/lists/us.archive.ubuntu.com_ubuntu_dists_focal-backports_main_i18n_Translation-en
[1;0m[1;36mVERBOSE: /var/lib/apt/lists/us.archive.ubuntu.com_ubuntu_dists_focal-backports_main_i18n_Translation-en file synced to APT.
[1;0m[1;32mus.archive.ubuntu.com_ubuntu_dists_focal-backports_main_i18n_Translation-en.xz synced.
[1;0m[1;36mVERBOSE: Synchronized file to /var/lib/apt/lists/us.archive.ubuntu.com_ubuntu_dists_focal-backports_multiverse_binary-amd64_Packages
[1;0m[1;36mVERBOSE: /var/lib/apt/lists/us.archive.ubuntu.com_ubuntu_dists_focal-backports_multiverse_binary-amd64_Packages file synced to APT.
[1;0m[1;32mus.archive.ubuntu.com_ubuntu_dists_focal-backports_multiverse_binary-amd64_Packages.xz synced.
```


The only issue is the extra sring about security updates being thrown. That is fixed in `master`. Hopefully over New Year holidays I'll be able to do a release.

**Comment by eamoncaddigan** [comment]
I'm also having an issue with packages not installing, I'm running apt-offline 1.8.2 on a fresh install of Raspberry Pi OS (bullseye 32-bit).

I do see some errors about broken URIs in `apt-offline set`, but it seems like they're safe to ignore: the packages that are slated for upgrade do appear as debs in my bundle after running `apt-offline get`. I don't see any errors when running `apt-offline install` with `--verbose`, but the packages are simply not installed.

I'm not sure if this is the same issue as OP's, and I don't know how to troubleshoot this further.

**Comment by rickysarraf** [comment]
This should be fixed with the latest release, which is `v1.8.3`
