### ISSUE TITLE
bug with bogus path

### ISSUE THREAD

**Issue by rickysarraf** [rickysarraf/apt-offline#37]
Executing command `'install /tmp/apt-offline-tests-9285.zip --simulate --skip-bug-reports'`
```
Installing src package file icewm_1.3.8+githubmod+20150914+fa3fdef-2.dsc to /tmp/apt-offline-src-downloads-26071.
ERROR: Failed to unlink /tmp/apt-update-target-path-26071/lxde-metapackages_6.tar.xzapt-offline
Installing src package file lxde-metapackages_6.dsc to /tmp/apt-offline-src-downloads-26071.
Installing src package file eclipse_3.8.1-8.dsc to /tmp/apt-offline-src-downloads-26071.
ERROR: Failed to unlink /tmp/apt-update-target-path-26071/icewm_1.3.8+githubmod+20150914+fa3fdef-2.debian.tar.xzapt-offline
ERROR: Failed to unlink /tmp/apt-update-target-path-26071/eclipse_3.8.1-8.debian.tar.xzapt-offline
ERROR: Failed to unlink /tmp/apt-update-target-path-26071/icewm_1.3.8+githubmod+20150914+fa3fdef.orig.tar.xzapt-offline
ant-optional_1.9.6-1_all.deb file synced.
libaspectj-java_1.8.5-1_all.deb file synced.
aspectj_1.8.5-1_all.deb file synced.
ant_1.9.6-1_all.deb file synced.
libxml-namespacesupport-perl_1.11-1_all.deb file synced.
libxml-sax-base-perl_1.07-1_all.deb file synced.
libxml-sax-expat-perl_0.40-2_all.deb file synced.
libintl-perl_1.24-1_all.deb file synced.


and


Executing command 'install /tmp/apt-offline-tests-9285.zip --skip-bug-reports'
Installing src package file icewm_1.3.8+githubmod+20150914+fa3fdef-2.dsc to /tmp/apt-offline-src-downloads-26108.
ERROR: Failed to unlink /tmp/apt-update-target-path-26108/lxde-metapackages_6.tar.xzapt-offline
Installing src package file lxde-metapackages_6.dsc to /tmp/apt-offline-src-downloads-26108.
Installing src package file eclipse_3.8.1-8.dsc to /tmp/apt-offline-src-downloads-26108.
ERROR: Failed to unlink /tmp/apt-update-target-path-26108/icewm_1.3.8+githubmod+20150914+fa3fdef-2.debian.tar.xzapt-offline
ERROR: Failed to unlink /tmp/apt-update-target-path-26108/eclipse_3.8.1-8.debian.tar.xzapt-offline
ERROR: Failed to unlink /tmp/apt-update-target-path-26108/icewm_1.3.8+githubmod+20150914+fa3fdef.orig.tar.xzapt-offline
ant-optional_1.9.6-1_all.deb file synced.
libaspectj-java_1.8.5-1_all.deb file synced.
aspectj_1.8.5-1_all.deb file synced.
ant_1.9.6-1_all.deb file synced.
libxml-namespacesupport-perl_1.11-1_all.deb file synced.
libxml-sax-base-perl_1.07-1_all.deb file synced.
libxml-sax-expat-perl_0.40-2_all.deb file synced.
libintl-perl_1.24-1_all.deb file synced.
```

**Comment by rickysarraf** [comment]
This was fixed with 4f6d64ec6881a864a8090c217b656e5101e8fc6d

**Comment by engcheng** [comment]
Hi @rickysarraf, I just cloned the repo and followed instructions from INSTALLATION and README.

However, its seems that the error still happening, where I got the following:

1. ERROR: Failed to sync file /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_xenial-security_restricted_binary-i386_Packages

2. WARN: Failed to unlink temproary file /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_xenial-security_restricted_binary-i386_Packagesapt-
offline. Check respective decompressor library support

Both the ONLINE and OFFLINE systems are running Ubuntu 16.04.1 64bits

Did I miss any steps?

**Comment by rickysarraf** [comment]
Do you have python-lzma installed ?

You mentioned you cloned the repo and are using the master revision. Can you share your complete console output ?

**Comment by engcheng** [comment]
Yes, python-lzma was installed.

On the ONLINE system: 

$ sudo apt-cache policy python-lzma

> python-lzma:
>   Installed: 0.5.3-3
>   Candidate: 0.5.3-3
>   Version table:
>  *** 0.5.3-3 500
>         500 http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
>         100 /var/lib/dpkg/status

$ sudo apt-get install python-lzma

> Reading package lists...
> Building dependency tree...
> Reading state information...
> python-lzma is already the newest version (0.5.3-3).
> 0 upgraded, 0 newly installed, 0 to remove and 58 not upgraded.

Errors from the OFFLINE system:

> ERROR: Failed to sync file /var/
> lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_xenial-security_restricte
> d_binary-i386_Packages
> WARN: Failed to unlink temproary file /var/lib/apt/lists/partial/secu
> rity.ubuntu.com_ubuntu_dists_xenial-security_restricted_binary-i386_Packagesapt-
> offline. Check respective decompressor library support
> ERROR: Failed to sync file /var/lib/apt/lists/partial/security.ubuntu
> .com_ubuntu_dists_xenial-security_main_binary-amd64_Packages
> WARN: Failed to unlink temproary file /var/lib/apt/lists/partial/secu
> rity.ubuntu.com_ubuntu_dists_xenial-security_main_binary-amd64_Packagesapt-offli
> ne. Check respective decompressor library support
> ERROR: Failed to sync file /var/lib/apt/lists/partial/security.ubuntu
> .com_ubuntu_dists_xenial-security_restricted_i18n_Translation-en
> WARN: Failed to unlink temproary file /var/lib/apt/lists/partial/secu
> rity.ubuntu.com_ubuntu_dists_xenial-security_restricted_i18n_Translation-enapt-o
> ffline. Check respective decompressor library support
> ERROR: Failed to sync file /var/lib/apt/lists/partial/security.ubuntu
> .com_ubuntu_dists_xenial-security_main_i18n_Translation-en
> WARN: Failed to unlink temproary file /var/lib/apt/lists/partial/secu
> rity.ubuntu.com_ubuntu_dists_xenial-security_main_i18n_Translation-enapt-offline
> . Check respective decompressor library support
> ERROR: Failed to sync file /var/lib/apt/lists/partial/security.ubuntu
> .com_ubuntu_dists_xenial-security_restricted_binary-amd64_Packages
> WARN: Failed to unlink temproary file /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_xenial-security_restricted_binary-amd64_Packagesapt-offline
> . Check respective decompressor library support
> ERROR: Failed to sync file /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_xenial-security_universe_binary-i386_Packages
> WARN: Failed to unlink temproary file /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_xenial-security_universe_binary-i386_Packagesapt-offline. C
> heck respective decompressor library support
> ERROR: Failed to sync file /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_xenial-security_universe_i18n_Translation-en
> WARN: Failed to unlink temproary file /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_xenial-security_universe_i18n_Translation-enapt-offline. Ch
> eck respective decompressor library support
> ERROR: Failed to sync file /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_xenial-security_multiverse_binary-amd64_Packages
> WARN: Failed to unlink temproary file /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_xenial-security_multiverse_binary-amd64_Packagesapt-offline
> . Check respective decompressor library support
> ERROR: Failed to sync file /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_xenial-security_multiverse_binary-i386_Packages
> WARN: Failed to unlink temproary file /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_xenial-security_multiverse_binary-i386_Packagesapt-offline.
>  Check respective decompressor library support
> ERROR: Failed to sync file /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_xenial-security_multiverse_i18n_Translation-en
> WARN: Failed to unlink temproary file /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_xenial-security_multiverse_i18n_Translation-enapt-offline. 
> Check respective decompressor library support
> ERROR: Failed to sync file /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_xenial-security_main_binary-i386_Packages
> WARN: Failed to unlink temproary file /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_xenial-security_main_binary-i386_Packagesapt-offline. Check
>  respective decompressor library support
> ERROR: Failed to sync file /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_xenial-security_universe_binary-amd64_Packages
> WARN: Failed to unlink temproary file /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_xenial-security_universe_binary-amd64_Packagesapt-offline. 
> Check respective decompressor library support
> ERROR: Failed to sync file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial_restricted_binary-amd64_Packages
> WARN: Failed to unlink temproary file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial_restricted_binary-amd64_Packagesapt-offline. Check
>  respective decompressor library support
> ERROR: Failed to sync file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial_restricted_binary-i386_Packages
> WARN: Failed to unlink temproary file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial_restricted_binary-i386_Packagesapt-offline. Check 
> respective decompressor library support
> ERROR: Failed to sync file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial_main_binary-amd64_Packages
> WARN: Failed to unlink temproary file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial_main_binary-amd64_Packagesapt-offline. Check respe
> ctive decompressor library support
> ERROR: Failed to sync file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial_main_i18n_Translation-en
> WARN: Failed to unlink temproary file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial_main_i18n_Translation-enapt-offline. Check respect
> ive decompressor library support
> ERROR: Failed to sync file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial_main_binary-i386_Packages
> WARN: Failed to unlink temproary file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial_main_binary-i386_Packagesapt-offline. Check respec
> tive decompressor library support
> ERROR: Failed to sync file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial_restricted_i18n_Translation-en
> WARN: Failed to unlink temproary file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial_restricted_i18n_Translation-enapt-offline. Check r
> espective decompressor library support
> ERROR: Failed to sync file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial_multiverse_binary-amd64_Packages
> WARN: Failed to unlink temproary file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial_multiverse_binary-amd64_Packagesapt-offline. Check
>  respective decompressor library support
> ERROR: Failed to sync file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial_multiverse_binary-i386_Packages
> WARN: Failed to unlink temproary file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial_multiverse_binary-i386_Packagesapt-offline. Check 
> respective decompressor library support
> ERROR: Failed to sync file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial_multiverse_i18n_Translation-en
> WARN: Failed to unlink temproary file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial_multiverse_i18n_Translation-enapt-offline. Check r
> espective decompressor library support
> ERROR: Failed to sync file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial_universe_i18n_Translation-en
> WARN: Failed to unlink temproary file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial_universe_i18n_Translation-enapt-offline. Check res
> pective decompressor library support
> ERROR: Failed to sync file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial-updates_main_binary-i386_Packages
> WARN: Failed to unlink temproary file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial-updates_main_binary-i386_Packagesapt-offline. Chec
> k respective decompressor library support
> ERROR: Failed to sync file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial-updates_main_binary-amd64_Packages
> WARN: Failed to unlink temproary file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial-updates_main_binary-amd64_Packagesapt-offline. Che
> ck respective decompressor library support
> ERROR: Failed to sync file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial-updates_restricted_binary-i386_Packages
> WARN: Failed to unlink temproary file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial-updates_restricted_binary-i386_Packagesapt-offline
> . Check respective decompressor library support
> ERROR: Failed to sync file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial-updates_main_i18n_Translation-en
> WARN: Failed to unlink temproary file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial-updates_main_i18n_Translation-enapt-offline. Check
>  respective decompressor library support
> ERROR: Failed to sync file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial_universe_binary-amd64_Packages
> WARN: Failed to unlink temproary file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial_universe_binary-amd64_Packagesapt-offline. Check r
> espective decompressor library support
> ERROR: Failed to sync file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial-updates_restricted_i18n_Translation-en
> WARN: Failed to unlink temproary file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial-updates_restricted_i18n_Translation-enapt-offline.
>  Check respective decompressor library support
> ERROR: Failed to sync file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial-updates_universe_i18n_Translation-en
> WARN: Failed to unlink temproary file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial-updates_universe_i18n_Translation-enapt-offline. C
> heck respective decompressor library support
> ERROR: Failed to sync file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial-backports_main_i18n_Translation-en
> WARN: Failed to unlink temproary file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial-backports_main_i18n_Translation-enapt-offline. Che
> ck respective decompressor library support
> ERROR: Failed to sync file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial-backports_restricted_binary-amd64_Packages
> WARN: Failed to unlink temproary file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial-backports_restricted_binary-amd64_Packagesapt-offl
> ine. Check respective decompressor library support
> ERROR: Failed to sync file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial-backports_restricted_binary-i386_Packages
> WARN: Failed to unlink temproary file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial-backports_restricted_binary-i386_Packagesapt-offli
> ne. Check respective decompressor library support
> ERROR: Failed to sync file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial-backports_main_binary-amd64_Packages
> WARN: Failed to unlink temproary file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial-backports_main_binary-amd64_Packagesapt-offline. C
> heck respective decompressor library support
> ERROR: Failed to sync file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial-backports_universe_i18n_Translation-en
> WARN: Failed to unlink temproary file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial-backports_universe_i18n_Translation-enapt-offline.
>  Check respective decompressor library support
> ERROR: Failed to sync file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial-backports_multiverse_binary-amd64_Packages
> WARN: Failed to unlink temproary file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial-backports_multiverse_binary-amd64_Packagesapt-offl
> ine. Check respective decompressor library support
> ERROR: Failed to sync file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial-backports_multiverse_binary-i386_Packages
> WARN: Failed to unlink temproary file /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial-backports_multiverse_binary-i386_Packagesapt-offli
> ne. Check respective decompressor library support
> gpgv: Signature made Mon 17 Oct 2016 10:46:51 PM PDT using DSA key ID 437D05B5
> gpgv: Good signature from "Ubuntu Archive Automatic Signing Key <ftpmaster@ubuntu.com>"
> gpgv: Signature made Mon 17 Oct 2016 10:46:51 PM PDT using RSA key ID C0B21F32
> gpgv: Good signature from "Ubuntu Archive Automatic Signing Key (2012) <ftpmaster@ubuntu.com>"
> ERROR: /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial-backports_Release is bad. Can't proceed.
> ERROR: /var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial-backports_Release.gpg bad signature. Not syncing because in strict mode.
> gpgv: Signature made Wed 19 Oct 2016 02:00:49 AM PDT using DSA key ID 437D05B5
> gpgv: Good signature from "Ubuntu Archive Automatic Signing Key <ftpmaster@ubuntu.com>"
> gpgv: Signature made Wed 19 Oct 2016 02:00:49 AM PDT using RSA key ID C0B21F32
> gpgv: Good signature from "Ubuntu Archive Automatic Signing Key (2012) <ftpmaster@ubuntu.com>"
> gpgv: Signature made Thu 21 Apr 2016 04:25:09 PM PDT using DSA key ID 437D05B5
> gpgv: Good signature from "Ubuntu Archive Automatic Signing Key <ftpmaster@ubuntu.com>"
> gpgv: Signature made Thu 21 Apr 2016 04:25:09 PM PDT using RSA key ID C0B21F32
> gpgv: Good signature from "Ubuntu Archive Automatic Signing Key (2012) <ftpmaster@ubuntu.com>"

Is this sufficient? Do you need any other information?

**Comment by rickysarraf** [comment]
No. Do you have python-lzma installed on the OFFLINE system ?

Please paste full console log of what you executed on the offline machine. I'm interested to see the arguments that are needed to understand the mode of execution.

**Comment by engcheng** [comment]
Thanks @rickysarraf . You're right that the cause of issue was due to python-lzma not present.

Once python-lzma is installed, the OFFLINE system is able to parse everything correctly.

**Comment by rickysarraf** [comment]
Glad it worked for you. I added a requirements.txt file, for users, who may be using apt-offline directly from the repository.
https://github.com/rickysarraf/apt-offline/commit/41df6467407e6cd741424c89a3d6322790ac186a
