### ISSUE TITLE
Script not found during installation

### ISSUE THREAD

**Issue by sylvainpelissier** [rickysarraf/apt-offline#85]
During a fresh installation I have the following errors:

```
running build
running build_py
file apt_offline_gui/resources_rc.py (for module apt_offline_gui.resources_rc) not found
file apt_offline_gui/Ui_AptOfflineQtAbout.py (for module apt_offline_gui.Ui_AptOfflineQtAbout) not found
file apt_offline_gui/Ui_AptOfflineQtCreateProfile.py (for module apt_offline_gui.Ui_AptOfflineQtCreateProfile) not found
file apt_offline_gui/Ui_AptOfflineQtFetch.py (for module apt_offline_gui.Ui_AptOfflineQtFetch) not found
file apt_offline_gui/Ui_AptOfflineQtFetchOptions.py (for module apt_offline_gui.Ui_AptOfflineQtFetchOptions) not found
file apt_offline_gui/Ui_AptOfflineQtInstall.py (for module apt_offline_gui.Ui_AptOfflineQtInstall) not found
file apt_offline_gui/Ui_AptOfflineQtInstallBugList.py (for module apt_offline_gui.Ui_AptOfflineQtInstallBugList) not found
file apt_offline_gui/Ui_AptOfflineQtInstallChangelog.py (for module apt_offline_gui.Ui_AptOfflineQtInstallChangelog) not found
file apt_offline_gui/Ui_AptOfflineQtMain.py (for module apt_offline_gui.Ui_AptOfflineQtMain) not found
file apt_offline_gui/Ui_AptOfflineQtSaveZip.py (for module apt_offline_gui.Ui_AptOfflineQtSaveZip) not found
file apt_offline_gui/resources_rc.py (for module apt_offline_gui.resources_rc) not found
file apt_offline_gui/Ui_AptOfflineQtAbout.py (for module apt_offline_gui.Ui_AptOfflineQtAbout) not found
file apt_offline_gui/Ui_AptOfflineQtCreateProfile.py (for module apt_offline_gui.Ui_AptOfflineQtCreateProfile) not found
file apt_offline_gui/Ui_AptOfflineQtFetch.py (for module apt_offline_gui.Ui_AptOfflineQtFetch) not found
file apt_offline_gui/Ui_AptOfflineQtFetchOptions.py (for module apt_offline_gui.Ui_AptOfflineQtFetchOptions) not found
file apt_offline_gui/Ui_AptOfflineQtInstall.py (for module apt_offline_gui.Ui_AptOfflineQtInstall) not found
file apt_offline_gui/Ui_AptOfflineQtInstallBugList.py (for module apt_offline_gui.Ui_AptOfflineQtInstallBugList) not found
file apt_offline_gui/Ui_AptOfflineQtInstallChangelog.py (for module apt_offline_gui.Ui_AptOfflineQtInstallChangelog) not found
file apt_offline_gui/Ui_AptOfflineQtMain.py (for module apt_offline_gui.Ui_AptOfflineQtMain) not found
file apt_offline_gui/Ui_AptOfflineQtSaveZip.py (for module apt_offline_gui.Ui_AptOfflineQtSaveZip) not found
running build_scripts
```
Finally the same modules will be missing if apt-offline-gui is executed.

**Comment by rickysarraf** [comment]
How are you building ?

```
rrs@priyasi:~/rrs-home/devel/apt-offline/apt-offline (master)$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
13:33 ♒♒♒   ☺ 😄    
rrs@priyasi:~/rrs-home/devel/apt-offline/apt-offline (master)$ python3 setup.py build
running build
running build_py
creating build
creating build/lib
creating build/lib/apt_offline_core
copying apt_offline_core/__init__.py -> build/lib/apt_offline_core
copying apt_offline_core/AptOfflineCoreLib.py -> build/lib/apt_offline_core
copying apt_offline_core/AptOfflineDebianBtsLib.py -> build/lib/apt_offline_core
copying apt_offline_core/AptOfflineLib.py -> build/lib/apt_offline_core
copying apt_offline_core/AptOfflineMagicLib.py -> build/lib/apt_offline_core
creating build/lib/apt_offline_gui
copying apt_offline_gui/__init__.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtAbout.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtCommon.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtCreateProfile.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtFetch.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtFetchOptions.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtInstall.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtInstallBugList.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtInstallChangelog.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtMain.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtSaveZip.py -> build/lib/apt_offline_gui
copying apt_offline_gui/QtProgressBar.py -> build/lib/apt_offline_gui
copying apt_offline_gui/resources_rc.py -> build/lib/apt_offline_gui
copying apt_offline_gui/Ui_AptOfflineQtAbout.py -> build/lib/apt_offline_gui
copying apt_offline_gui/Ui_AptOfflineQtCreateProfile.py -> build/lib/apt_offline_gui
copying apt_offline_gui/Ui_AptOfflineQtFetch.py -> build/lib/apt_offline_gui
copying apt_offline_gui/Ui_AptOfflineQtFetchOptions.py -> build/lib/apt_offline_gui
copying apt_offline_gui/Ui_AptOfflineQtInstall.py -> build/lib/apt_offline_gui
copying apt_offline_gui/Ui_AptOfflineQtInstallBugList.py -> build/lib/apt_offline_gui
copying apt_offline_gui/Ui_AptOfflineQtInstallChangelog.py -> build/lib/apt_offline_gui
copying apt_offline_gui/Ui_AptOfflineQtMain.py -> build/lib/apt_offline_gui
copying apt_offline_gui/Ui_AptOfflineQtSaveZip.py -> build/lib/apt_offline_gui
copying apt_offline_gui/UiDataStructs.py -> build/lib/apt_offline_gui
running build_scripts
creating build/scripts-3.6
copying and adjusting apt-offline -> build/scripts-3.6
copying and adjusting apt-offline-gui -> build/scripts-3.6
changing mode of build/scripts-3.6/apt-offline from 644 to 755
changing mode of build/scripts-3.6/apt-offline-gui from 644 to 755
13:33 ♒♒♒   ☺ 😄    
```

**Comment by sylvainpelissier** [comment]
I am building exactly the same:

```
sylvain@sylvain-VirtualBox:~/apt-offline$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
sylvain@sylvain-VirtualBox:~/apt-offline$ python3 setup.py build
running build
running build_py
file apt_offline_gui/resources_rc.py (for module apt_offline_gui.resources_rc) not found
file apt_offline_gui/Ui_AptOfflineQtAbout.py (for module apt_offline_gui.Ui_AptOfflineQtAbout) not found
file apt_offline_gui/Ui_AptOfflineQtCreateProfile.py (for module apt_offline_gui.Ui_AptOfflineQtCreateProfile) not found
file apt_offline_gui/Ui_AptOfflineQtFetch.py (for module apt_offline_gui.Ui_AptOfflineQtFetch) not found
file apt_offline_gui/Ui_AptOfflineQtFetchOptions.py (for module apt_offline_gui.Ui_AptOfflineQtFetchOptions) not found
file apt_offline_gui/Ui_AptOfflineQtInstall.py (for module apt_offline_gui.Ui_AptOfflineQtInstall) not found
file apt_offline_gui/Ui_AptOfflineQtInstallBugList.py (for module apt_offline_gui.Ui_AptOfflineQtInstallBugList) not found
file apt_offline_gui/Ui_AptOfflineQtInstallChangelog.py (for module apt_offline_gui.Ui_AptOfflineQtInstallChangelog) not found
file apt_offline_gui/Ui_AptOfflineQtMain.py (for module apt_offline_gui.Ui_AptOfflineQtMain) not found
file apt_offline_gui/Ui_AptOfflineQtSaveZip.py (for module apt_offline_gui.Ui_AptOfflineQtSaveZip) not found
creating build
creating build/lib
creating build/lib/apt_offline_core
copying apt_offline_core/__init__.py -> build/lib/apt_offline_core
copying apt_offline_core/AptOfflineCoreLib.py -> build/lib/apt_offline_core
copying apt_offline_core/AptOfflineDebianBtsLib.py -> build/lib/apt_offline_core
copying apt_offline_core/AptOfflineLib.py -> build/lib/apt_offline_core
copying apt_offline_core/AptOfflineMagicLib.py -> build/lib/apt_offline_core
creating build/lib/apt_offline_gui
copying apt_offline_gui/__init__.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtAbout.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtCommon.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtCreateProfile.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtFetch.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtFetchOptions.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtInstall.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtInstallBugList.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtInstallChangelog.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtMain.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtSaveZip.py -> build/lib/apt_offline_gui
copying apt_offline_gui/QtProgressBar.py -> build/lib/apt_offline_gui
copying apt_offline_gui/UiDataStructs.py -> build/lib/apt_offline_gui
file apt_offline_gui/resources_rc.py (for module apt_offline_gui.resources_rc) not found
file apt_offline_gui/Ui_AptOfflineQtAbout.py (for module apt_offline_gui.Ui_AptOfflineQtAbout) not found
file apt_offline_gui/Ui_AptOfflineQtCreateProfile.py (for module apt_offline_gui.Ui_AptOfflineQtCreateProfile) not found
file apt_offline_gui/Ui_AptOfflineQtFetch.py (for module apt_offline_gui.Ui_AptOfflineQtFetch) not found
file apt_offline_gui/Ui_AptOfflineQtFetchOptions.py (for module apt_offline_gui.Ui_AptOfflineQtFetchOptions) not found
file apt_offline_gui/Ui_AptOfflineQtInstall.py (for module apt_offline_gui.Ui_AptOfflineQtInstall) not found
file apt_offline_gui/Ui_AptOfflineQtInstallBugList.py (for module apt_offline_gui.Ui_AptOfflineQtInstallBugList) not found
file apt_offline_gui/Ui_AptOfflineQtInstallChangelog.py (for module apt_offline_gui.Ui_AptOfflineQtInstallChangelog) not found
file apt_offline_gui/Ui_AptOfflineQtMain.py (for module apt_offline_gui.Ui_AptOfflineQtMain) not found
file apt_offline_gui/Ui_AptOfflineQtSaveZip.py (for module apt_offline_gui.Ui_AptOfflineQtSaveZip) not found
running build_scripts
creating build/scripts-3.6
copying and adjusting apt-offline -> build/scripts-3.6
copying and adjusting apt-offline-gui -> build/scripts-3.6
changing mode of build/scripts-3.6/apt-offline from 644 to 755
changing mode of build/scripts-3.6/apt-offline-gui from 644 to 755
```

**Comment by rickysarraf** [comment]
Thanks. I've reproduced it now, after doing a fresh clone

```
rrs@priyasi:/tmp$ git clone git@github.com:rickysarraf/apt-offline.git
Cloning into 'apt-offline'...
X11 forwarding request failed on channel 1
remote: Counting objects: 6864, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 6864 (delta 1), reused 0 (delta 0), pack-reused 6858
Receiving objects: 100% (6864/6864), 2.26 MiB | 1008.00 KiB/s, done.
Resolving deltas: 100% (3897/3897), done.
09:39 ♒♒♒   ☺ 😄    
rrs@priyasi:/tmp$ cd apt-offline/
09:39 ♒♒♒   ☺ 😄    
rrs@priyasi:/tmp/apt-offline (master)$ python3 setup.py build
running build
running build_py
file apt_offline_gui/resources_rc.py (for module apt_offline_gui.resources_rc) not found
file apt_offline_gui/Ui_AptOfflineQtAbout.py (for module apt_offline_gui.Ui_AptOfflineQtAbout) not found
file apt_offline_gui/Ui_AptOfflineQtCreateProfile.py (for module apt_offline_gui.Ui_AptOfflineQtCreateProfile) not found
file apt_offline_gui/Ui_AptOfflineQtFetch.py (for module apt_offline_gui.Ui_AptOfflineQtFetch) not found
file apt_offline_gui/Ui_AptOfflineQtFetchOptions.py (for module apt_offline_gui.Ui_AptOfflineQtFetchOptions) not found
file apt_offline_gui/Ui_AptOfflineQtInstall.py (for module apt_offline_gui.Ui_AptOfflineQtInstall) not found
file apt_offline_gui/Ui_AptOfflineQtInstallBugList.py (for module apt_offline_gui.Ui_AptOfflineQtInstallBugList) not found
file apt_offline_gui/Ui_AptOfflineQtInstallChangelog.py (for module apt_offline_gui.Ui_AptOfflineQtInstallChangelog) not found
file apt_offline_gui/Ui_AptOfflineQtMain.py (for module apt_offline_gui.Ui_AptOfflineQtMain) not found
file apt_offline_gui/Ui_AptOfflineQtSaveZip.py (for module apt_offline_gui.Ui_AptOfflineQtSaveZip) not found
creating build
creating build/lib
creating build/lib/apt_offline_core
copying apt_offline_core/__init__.py -> build/lib/apt_offline_core
copying apt_offline_core/AptOfflineCoreLib.py -> build/lib/apt_offline_core
copying apt_offline_core/AptOfflineDebianBtsLib.py -> build/lib/apt_offline_core
copying apt_offline_core/AptOfflineLib.py -> build/lib/apt_offline_core
copying apt_offline_core/AptOfflineMagicLib.py -> build/lib/apt_offline_core
creating build/lib/apt_offline_gui
copying apt_offline_gui/__init__.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtAbout.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtCommon.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtCreateProfile.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtFetch.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtFetchOptions.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtInstall.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtInstallBugList.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtInstallChangelog.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtMain.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtSaveZip.py -> build/lib/apt_offline_gui
copying apt_offline_gui/QtProgressBar.py -> build/lib/apt_offline_gui
copying apt_offline_gui/UiDataStructs.py -> build/lib/apt_offline_gui
file apt_offline_gui/resources_rc.py (for module apt_offline_gui.resources_rc) not found
file apt_offline_gui/Ui_AptOfflineQtAbout.py (for module apt_offline_gui.Ui_AptOfflineQtAbout) not found
file apt_offline_gui/Ui_AptOfflineQtCreateProfile.py (for module apt_offline_gui.Ui_AptOfflineQtCreateProfile) not found
file apt_offline_gui/Ui_AptOfflineQtFetch.py (for module apt_offline_gui.Ui_AptOfflineQtFetch) not found
file apt_offline_gui/Ui_AptOfflineQtFetchOptions.py (for module apt_offline_gui.Ui_AptOfflineQtFetchOptions) not found
file apt_offline_gui/Ui_AptOfflineQtInstall.py (for module apt_offline_gui.Ui_AptOfflineQtInstall) not found
file apt_offline_gui/Ui_AptOfflineQtInstallBugList.py (for module apt_offline_gui.Ui_AptOfflineQtInstallBugList) not found
file apt_offline_gui/Ui_AptOfflineQtInstallChangelog.py (for module apt_offline_gui.Ui_AptOfflineQtInstallChangelog) not found
file apt_offline_gui/Ui_AptOfflineQtMain.py (for module apt_offline_gui.Ui_AptOfflineQtMain) not found
file apt_offline_gui/Ui_AptOfflineQtSaveZip.py (for module apt_offline_gui.Ui_AptOfflineQtSaveZip) not found
running build_scripts
creating build/scripts-3.6
copying and adjusting apt-offline -> build/scripts-3.6
copying and adjusting apt-offline-gui -> build/scripts-3.6
changing mode of build/scripts-3.6/apt-offline from 644 to 755
changing mode of build/scripts-3.6/apt-offline-gui from 644 to 755
09:39 ♒♒♒   ☺ 😄    
```

**Comment by rickysarraf** [comment]
Thanks for the report. Please pull changes from the git repo. The issue is fixed now.

**Comment by sylvainpelissier** [comment]
Sorry but I still have the same problem with a fresh git clone:

```
sylvain@sylvain-VirtualBox:~/apt-offline$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
sylvain@sylvain-VirtualBox:~/apt-offline$ python3 setup.py build
running build
running build_py
file apt_offline_gui/resources_rc.py (for module apt_offline_gui.resources_rc) not found
file apt_offline_gui/Ui_AptOfflineQtAbout.py (for module apt_offline_gui.Ui_AptOfflineQtAbout) not found
file apt_offline_gui/Ui_AptOfflineQtCreateProfile.py (for module apt_offline_gui.Ui_AptOfflineQtCreateProfile) not found
file apt_offline_gui/Ui_AptOfflineQtFetch.py (for module apt_offline_gui.Ui_AptOfflineQtFetch) not found
file apt_offline_gui/Ui_AptOfflineQtFetchOptions.py (for module apt_offline_gui.Ui_AptOfflineQtFetchOptions) not found
file apt_offline_gui/Ui_AptOfflineQtInstall.py (for module apt_offline_gui.Ui_AptOfflineQtInstall) not found
file apt_offline_gui/Ui_AptOfflineQtInstallBugList.py (for module apt_offline_gui.Ui_AptOfflineQtInstallBugList) not found
file apt_offline_gui/Ui_AptOfflineQtInstallChangelog.py (for module apt_offline_gui.Ui_AptOfflineQtInstallChangelog) not found
file apt_offline_gui/Ui_AptOfflineQtMain.py (for module apt_offline_gui.Ui_AptOfflineQtMain) not found
file apt_offline_gui/Ui_AptOfflineQtSaveZip.py (for module apt_offline_gui.Ui_AptOfflineQtSaveZip) not found
creating build
creating build/lib
creating build/lib/apt_offline_core
copying apt_offline_core/__init__.py -> build/lib/apt_offline_core
copying apt_offline_core/AptOfflineCoreLib.py -> build/lib/apt_offline_core
copying apt_offline_core/AptOfflineDebianBtsLib.py -> build/lib/apt_offline_core
copying apt_offline_core/AptOfflineLib.py -> build/lib/apt_offline_core
copying apt_offline_core/AptOfflineMagicLib.py -> build/lib/apt_offline_core
creating build/lib/apt_offline_gui
copying apt_offline_gui/__init__.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtAbout.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtCommon.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtCreateProfile.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtFetch.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtFetchOptions.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtInstall.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtInstallBugList.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtInstallChangelog.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtMain.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtSaveZip.py -> build/lib/apt_offline_gui
copying apt_offline_gui/QtProgressBar.py -> build/lib/apt_offline_gui
copying apt_offline_gui/UiDataStructs.py -> build/lib/apt_offline_gui
file apt_offline_gui/resources_rc.py (for module apt_offline_gui.resources_rc) not found
file apt_offline_gui/Ui_AptOfflineQtAbout.py (for module apt_offline_gui.Ui_AptOfflineQtAbout) not found
file apt_offline_gui/Ui_AptOfflineQtCreateProfile.py (for module apt_offline_gui.Ui_AptOfflineQtCreateProfile) not found
file apt_offline_gui/Ui_AptOfflineQtFetch.py (for module apt_offline_gui.Ui_AptOfflineQtFetch) not found
file apt_offline_gui/Ui_AptOfflineQtFetchOptions.py (for module apt_offline_gui.Ui_AptOfflineQtFetchOptions) not found
file apt_offline_gui/Ui_AptOfflineQtInstall.py (for module apt_offline_gui.Ui_AptOfflineQtInstall) not found
file apt_offline_gui/Ui_AptOfflineQtInstallBugList.py (for module apt_offline_gui.Ui_AptOfflineQtInstallBugList) not found
file apt_offline_gui/Ui_AptOfflineQtInstallChangelog.py (for module apt_offline_gui.Ui_AptOfflineQtInstallChangelog) not found
file apt_offline_gui/Ui_AptOfflineQtMain.py (for module apt_offline_gui.Ui_AptOfflineQtMain) not found
file apt_offline_gui/Ui_AptOfflineQtSaveZip.py (for module apt_offline_gui.Ui_AptOfflineQtSaveZip) not found
running build_scripts
creating build/scripts-3.6
copying and adjusting apt-offline -> build/scripts-3.6
copying and adjusting apt-offline-gui -> build/scripts-3.6
changing mode of build/scripts-3.6/apt-offline from 644 to 755
changing mode of build/scripts-3.6/apt-offline-gui from 644 to 755
```

**Comment by rickysarraf** [comment]
My bad. I should have made a comment in this bug report. With this commit f3b9c76734997a317b9258406ef4642c16e7e053, now we use `make build` instead. Please update your repo and you should have an updated README.

**Comment by sylvainpelissier** [comment]
Still it have the same errors:

```
sylvain@sylvain-VirtualBox:~/apt-offline$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
sylvain@sylvain-VirtualBox:~/apt-offline$ make build
cd apt_offline_gui ; ./genui.sh
Compiling Ui files
Compiling file AptOfflineQtAbout.ui into Ui_AptOfflineQtAbout.py
./genui.sh: 12: ./genui.sh: pyuic5: not found
Compiling file AptOfflineQtCreateProfile.ui into Ui_AptOfflineQtCreateProfile.py
./genui.sh: 12: ./genui.sh: pyuic5: not found
Compiling file AptOfflineQtFetch.ui into Ui_AptOfflineQtFetch.py
./genui.sh: 12: ./genui.sh: pyuic5: not found
Compiling file AptOfflineQtFetchOptions.ui into Ui_AptOfflineQtFetchOptions.py
./genui.sh: 12: ./genui.sh: pyuic5: not found
Compiling file AptOfflineQtInstall.ui into Ui_AptOfflineQtInstall.py
./genui.sh: 12: ./genui.sh: pyuic5: not found
Compiling file AptOfflineQtInstallBugList.ui into Ui_AptOfflineQtInstallBugList.py
./genui.sh: 12: ./genui.sh: pyuic5: not found
Compiling file AptOfflineQtInstallChangelog.ui into Ui_AptOfflineQtInstallChangelog.py
./genui.sh: 12: ./genui.sh: pyuic5: not found
Compiling file AptOfflineQtMain.ui into Ui_AptOfflineQtMain.py
./genui.sh: 12: ./genui.sh: pyuic5: not found
Compiling file AptOfflineQtSaveZip.ui into Ui_AptOfflineQtSaveZip.py
./genui.sh: 12: ./genui.sh: pyuic5: not found
Compiling Resources files
./genui.sh: 16: ./genui.sh: pyrcc5: not found
Done
python3 setup.py build
running build
running build_py
file apt_offline_gui/resources_rc.py (for module apt_offline_gui.resources_rc) not found
file apt_offline_gui/Ui_AptOfflineQtAbout.py (for module apt_offline_gui.Ui_AptOfflineQtAbout) not found
file apt_offline_gui/Ui_AptOfflineQtCreateProfile.py (for module apt_offline_gui.Ui_AptOfflineQtCreateProfile) not found
file apt_offline_gui/Ui_AptOfflineQtFetch.py (for module apt_offline_gui.Ui_AptOfflineQtFetch) not found
file apt_offline_gui/Ui_AptOfflineQtFetchOptions.py (for module apt_offline_gui.Ui_AptOfflineQtFetchOptions) not found
file apt_offline_gui/Ui_AptOfflineQtInstall.py (for module apt_offline_gui.Ui_AptOfflineQtInstall) not found
file apt_offline_gui/Ui_AptOfflineQtInstallBugList.py (for module apt_offline_gui.Ui_AptOfflineQtInstallBugList) not found
file apt_offline_gui/Ui_AptOfflineQtInstallChangelog.py (for module apt_offline_gui.Ui_AptOfflineQtInstallChangelog) not found
file apt_offline_gui/Ui_AptOfflineQtMain.py (for module apt_offline_gui.Ui_AptOfflineQtMain) not found
file apt_offline_gui/Ui_AptOfflineQtSaveZip.py (for module apt_offline_gui.Ui_AptOfflineQtSaveZip) not found
creating build
creating build/lib
creating build/lib/apt_offline_core
copying apt_offline_core/__init__.py -> build/lib/apt_offline_core
copying apt_offline_core/AptOfflineCoreLib.py -> build/lib/apt_offline_core
copying apt_offline_core/AptOfflineDebianBtsLib.py -> build/lib/apt_offline_core
copying apt_offline_core/AptOfflineLib.py -> build/lib/apt_offline_core
copying apt_offline_core/AptOfflineMagicLib.py -> build/lib/apt_offline_core
creating build/lib/apt_offline_gui
copying apt_offline_gui/__init__.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtAbout.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtCommon.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtCreateProfile.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtFetch.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtFetchOptions.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtInstall.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtInstallBugList.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtInstallChangelog.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtMain.py -> build/lib/apt_offline_gui
copying apt_offline_gui/AptOfflineQtSaveZip.py -> build/lib/apt_offline_gui
copying apt_offline_gui/QtProgressBar.py -> build/lib/apt_offline_gui
copying apt_offline_gui/UiDataStructs.py -> build/lib/apt_offline_gui
file apt_offline_gui/resources_rc.py (for module apt_offline_gui.resources_rc) not found
file apt_offline_gui/Ui_AptOfflineQtAbout.py (for module apt_offline_gui.Ui_AptOfflineQtAbout) not found
file apt_offline_gui/Ui_AptOfflineQtCreateProfile.py (for module apt_offline_gui.Ui_AptOfflineQtCreateProfile) not found
file apt_offline_gui/Ui_AptOfflineQtFetch.py (for module apt_offline_gui.Ui_AptOfflineQtFetch) not found
file apt_offline_gui/Ui_AptOfflineQtFetchOptions.py (for module apt_offline_gui.Ui_AptOfflineQtFetchOptions) not found
file apt_offline_gui/Ui_AptOfflineQtInstall.py (for module apt_offline_gui.Ui_AptOfflineQtInstall) not found
file apt_offline_gui/Ui_AptOfflineQtInstallBugList.py (for module apt_offline_gui.Ui_AptOfflineQtInstallBugList) not found
file apt_offline_gui/Ui_AptOfflineQtInstallChangelog.py (for module apt_offline_gui.Ui_AptOfflineQtInstallChangelog) not found
file apt_offline_gui/Ui_AptOfflineQtMain.py (for module apt_offline_gui.Ui_AptOfflineQtMain) not found
file apt_offline_gui/Ui_AptOfflineQtSaveZip.py (for module apt_offline_gui.Ui_AptOfflineQtSaveZip) not found
running build_scripts
creating build/scripts-3.6
copying and adjusting apt-offline -> build/scripts-3.6
copying and adjusting apt-offline-gui -> build/scripts-3.6
changing mode of build/scripts-3.6/apt-offline from 644 to 755
changing mode of build/scripts-3.6/apt-offline-gui from 644 to 755

```

**Comment by rickysarraf** [comment]
No. This one has better errors reported. In your case, some of the tools are missing. On a Debian based system, you need to install `pyqt5-dev-tools`. On other distributions, you need to install the package that provides `pyuic5` and `pyrcc5`

```
Compiling file AptOfflineQtMain.ui into Ui_AptOfflineQtMain.py
./genui.sh: 12: ./genui.sh: pyuic5: not found
Compiling file AptOfflineQtSaveZip.ui into Ui_AptOfflineQtSaveZip.py
./genui.sh: 12: ./genui.sh: pyuic5: not found
Compiling Resources files
./genui.sh: 16: ./genui.sh: pyrcc5: not found
Done
```

**Comment by sylvainpelissier** [comment]
Yes sorry, it is working fine now. Thank you.
